name: Main

on:
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  run_release_please:
    name: Release Please
    uses: spuxx-dev/cicd/.github/workflows/release_please.yml@v1
    secrets:
      TOKEN: ${{ secrets.RELEASE_PLEASE_TOKEN }}
